[
    {
      id: "1",
      src: "https://images.pexels.com/photos/3408744/pexels-photo-3408744.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      alt: "Northern Winter Sky Image",
      title: "Northern Winter Sky",
      description:
        "A breathtaking view of the aurora borealis over a winter landscape.",
      tags: ["Nature", "Winter", "Aurora"],
      height: 750,
      likes: 345,
      prompt:
        "A wide shot of the northern lights dancing over a snowy forest, with clear stars in the sky.",
      orientation: "horizontal",
      color: "blue",
      gridSize: "large",
    },
    {
      id: "2",
      src: "https://images.pexels.com/photos/1142950/pexels-photo-1142950.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      alt: "Shining Stars Image",
      title: "Shining Stars",
      description: "A beautiful night sky filled with countless shining stars.",
      tags: ["Night", "Stars", "Sky"],
      height: 750,
      likes: 210,
      prompt:
        "Long exposure of a starry night sky over a dark landscape, focusing on the Milky Way.",
      orientation: "horizontal",
      color: "dark",
      gridSize: "wide",
    },
    {
      id: "3",
      src: "https://images.pexels.com/photos/3933881/pexels-photo-3933881.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      alt: "A River Flowing Image",
      title: "River Flow",
      description: "A serene river flowing through a lush green valley.",
      tags: ["Nature", "River", "Landscape"],
      height: 750,
      likes: 180,
      prompt:
        "A calm river winding through a vibrant green valley, with soft sunlight.",
      orientation: "horizontal",
      color: "green",
      gridSize: "wide",
    },
    {
      id: "4",
      src: "https://images.pexels.com/photos/5409751/pexels-photo-5409751.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      alt: "A cloudy Mountain Image",
      title: "Cloudy Mountain",
      description: "Majestic mountains shrouded in mystical clouds.",
      tags: ["Nature", "Mountain", "Clouds"],
      height: 750,
      likes: 95,
      prompt:
        "A dramatic view of a mountain peak partially obscured by swirling clouds.",
      orientation: "horizontal",
      color: "gray",
      gridSize: "normal",
    },
    {
      id: "5",
      src: "https://images.pexels.com/photos/4101555/pexels-photo-4101555.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      alt: "A Winter Rainbow Image",
      title: "Winter Rainbow",
      description: "A rare and beautiful rainbow appearing in a winter sky.",
      tags: ["Nature", "Winter", "Rainbow"],
      height: 750,
      likes: 130,
      prompt:
        "A vibrant rainbow arching over a snow-covered landscape during winter.",
      orientation: "horizontal",
      color: "white",
      gridSize: "normal",
    },
    {
      id: "6",
      src: "https://images.pexels.com/photos/443446/pexels-photo-443446.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      alt: "A Clean Mountain Lake",
      title: "Mountain Lake",
      description:
        "Crystal clear waters of a mountain lake reflecting the sky.",
      tags: ["Nature", "Lake", "Mountain"],
      height: 750,
      likes: 280,
      prompt:
        "An aerial view of a pristine mountain lake with clear blue water and surrounding pine trees.",
      orientation: "horizontal",
      color: "blue",
      gridSize: "wide",
    },
    {
      id: "7",
      src: "https://images.pexels.com/photos/1142950/pexels-photo-1142950.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      alt: "Shining Stars Image",
      title: "Shining Stars Again",
      description: "Another stunning capture of the night sky.",
      tags: ["Night", "Stars", "Sky"],
      height: 750,
      likes: 200,
      prompt:
        "A different perspective of a starry night, with a focus on a specific constellation.",
      orientation: "horizontal",
      color: "dark",
      gridSize: "normal",
    },
    {
      id: "8",
      src: "https://images.pexels.com/photos/1032650/pexels-photo-1032650.jpeg?auto=compress&cs=tinysrgb&w=800&h=1200&dpr=2",
      alt: "Cityscape at Sunset",
      title: "City Sunset",
      description:
        "Vibrant city skyline at dusk. A beautiful blend of urban architecture and natural light.",
      tags: ["City", "Sunset", "Urban"],
      height: 1200,
      likes: 450,
      prompt:
        "A wide shot of a modern city at sunset, with warm orange and purple hues in the sky, reflecting on glass buildings.",
      orientation: "vertical",
      color: "orange",
      gridSize: "large",
    },
    {
      id: "9",
      src: "https://images.pexels.com/photos/1054218/pexels-photo-1054218.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&dpr=2",
      alt: "Mountain Lake",
      title: "Alpine Serenity",
      description:
        "Tranquil lake surrounded by majestic snow-capped mountains under a clear sky.",
      tags: ["Nature", "Mountain", "Lake"],
      height: 1000,
      likes: 389,
      prompt:
        "A serene alpine lake reflecting snow-capped peaks, with crystal clear water and a deep blue sky.",
      orientation: "vertical",
      color: "blue",
      gridSize: "normal",
    },
    {
      id: "10",
      src: "https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg?auto=compress&cs=tinysrgb&w=800&h=1200&dpr=2",
      alt: "Abstract Light Trails",
      title: "Light Trails",
      description:
        "Dynamic light streaks in motion, creating an abstract and futuristic pattern.",
      tags: ["Abstract", "Light", "Motion"],
      height: 1200,
      likes: 510,
      prompt:
        "Long exposure photography of car lights on a winding road at night, creating vibrant light trails against a dark background.",
      orientation: "vertical",
      color: "purple",
      gridSize: "normal",
    },
    {
      id: "11",
      src: "https://images.pexels.com/photos/1122408/pexels-photo-1122408.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&dpr=2",
      alt: "Forest Road",
      title: "Enchanted Path",
      description:
        "A winding road through a dense, green forest, inviting exploration.",
      tags: ["Nature", "Forest", "Road"],
      height: 1000,
      likes: 275,
      prompt:
        "A narrow, winding dirt road disappearing into a dense, sun-dappled forest, with tall trees and lush undergrowth.",
      orientation: "vertical",
      color: "green",
      gridSize: "normal",
    },
    {
      id: "12",
      src: "https://images.pexels.com/photos/113338/pexels-photo-113338.jpeg?auto=compress&cs=tinysrgb&w=800&h=1200&dpr=2",
      alt: "Coffee Cup",
      title: "Morning Brew",
      description:
        "A cozy moment with a steaming cup of coffee on a rustic wooden table.",
      tags: ["Food", "Lifestyle", "Coffee"],
      height: 1200,
      likes: 150,
      prompt:
        "A close-up shot of a white ceramic coffee cup with steam rising, placed on a wooden table next to a window with soft morning light.",
      orientation: "vertical",
      color: "brown",
      gridSize: "large",
    },
    {
      id: "13",
      src: "https://images.pexels.com/photos/1169084/pexels-photo-1169084.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&dpr=2",
      alt: "Desert Landscape",
      title: "Arid Beauty",
      description:
        "Vast, untouched desert landscape with rolling sand dunes under a clear blue sky.",
      tags: ["Nature", "Desert", "Landscape"],
      height: 1000,
      likes: 60,
      prompt:
        "An expansive desert landscape featuring undulating sand dunes, with clear blue skies and harsh sunlight casting long shadows.",
      orientation: "vertical",
      color: "yellow",
      gridSize: "normal",
    },
    {
      id: "14",
      src: "https://images.pexels.com/photos/1206059/pexels-photo-1206059.jpeg?auto=compress&cs=tinysrgb&w=800&h=1200&dpr=2",
      alt: "Waterfall",
      title: "Cascading Waters",
      description:
        "A powerful waterfall in a lush, green environment, surrounded by vibrant foliage.",
      tags: ["Nature", "Waterfall", "Forest"],
      height: 1200,
      likes: 180,
      prompt:
        "A majestic waterfall with clear, powerful water cascading down rocks into a pool, surrounded by dense, green rainforest.",
      orientation: "vertical",
      color: "green",
      gridSize: "normal",
    },
    {
      id: "15",
      src: "https://images.pexels.com/photos/1229861/pexels-photo-1229861.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&dpr=2",
      alt: "Geometric Pattern",
      title: "Modern Geometry",
      description:
        "Intricate patterns in modern architecture, showcasing repetitive geometric forms.",
      tags: ["Abstract", "Architecture", "Pattern"],
      height: 1000,
      likes: 95,
      prompt:
        "A close-up of a modern building facade with repeating geometric patterns, focusing on lines and shadows.",
      orientation: "square",
      color: "gray",
      gridSize: "normal",
    },
    {
      id: "16",
      src: "https://images.pexels.com/photos/1236701/pexels-photo-1236701.jpeg?auto=compress&cs=tinysrgb&w=800&h=1200&dpr=2",
      alt: "Autumn Leaves",
      title: "Fall Colors",
      description:
        "Vibrant autumn leaves scattered on the ground, a tapestry of red, orange, and gold.",
      tags: ["Nature", "Autumn", "Leaves"],
      height: 1200,
      likes: 110,
      prompt:
        "A ground-level shot of a forest floor covered in colorful autumn leaves, with soft, diffused sunlight.",
      orientation: "square",
      color: "red",
      gridSize: "normal",
    },
    {
      id: "17",
      src: "https://images.pexels.com/photos/1269968/pexels-photo-1269968.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&dpr=2",
      alt: "Ocean Sunset",
      title: "Golden Hour",
      description:
        "A breathtaking sunset over the calm ocean, with a golden glow reflecting on the water.",
      tags: ["Nature", "Sunset", "Ocean"],
      height: 1000,
      likes: 250,
      prompt:
        "A wide shot of the ocean at sunset, with a vibrant orange and pink sky, and the sun's reflection on the water.",
      orientation: "square",
      color: "orange",
      gridSize: "large",
    },
    {
      id: "18",
      src: "https://images.pexels.com/photos/1309767/pexels-photo-1309767.jpeg?auto=compress&cs=tinysrgb&w=800&h=1200&dpr=2",
      alt: "City Night Lights",
      title: "Neon City",
      description:
        "Bright neon signs illuminating a bustling city street at night, creating a vibrant urban scene.",
      tags: ["City", "Night", "Neon"],
      height: 1200,
      likes: 190,
      prompt:
        "A busy city street at night, with blurred car lights and sharp, colorful neon signs illuminating the scene.",
      orientation: "square",
      color: "dark",
      gridSize: "normal",
    },
    {
      id: "19",
      src: "https://images.pexels.com/photos/1317232/pexels-photo-1317232.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&dpr=2",
      alt: "Abstract Paint",
      title: "Fluid Art",
      description:
        "Abstract painting with swirling colors, creating a sense of movement and depth.",
      tags: ["Art", "Abstract", "Fluid"],
      height: 1000,
      likes: 105,
      prompt:
        "A macro shot of fluid acrylic paint swirling, creating abstract patterns with vibrant blues, greens, and purples.",
      orientation: "square",
      color: "blue",
      gridSize: "normal",
    },
    {
      id: "q1",
      src: "https://images.pexels.com/photos/3408744/pexels-photo-3408744.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      alt: "Northern Winter Sky Image",
      title: "Northern Winter Sky",
      description:
        "A breathtaking view of the aurora borealis over a winter landscape.",
      tags: ["Nature", "Winter", "Aurora"],
      height: 750,
      likes: 345,
      prompt:
        "A wide shot of the northern lights dancing over a snowy forest, with clear stars in the sky.",
      orientation: "horizontal",
      color: "blue",
      gridSize: "large",
    },
    {
      id: "q2",
      src: "https://images.pexels.com/photos/1142950/pexels-photo-1142950.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      alt: "Shining Stars Image",
      title: "Shining Stars",
      description: "A beautiful night sky filled with countless shining stars.",
      tags: ["Night", "Stars", "Sky"],
      height: 750,
      likes: 210,
      prompt:
        "Long exposure of a starry night sky over a dark landscape, focusing on the Milky Way.",
      orientation: "horizontal",
      color: "dark",
      gridSize: "wide",
    },
    {
      id: "q3",
      src: "https://images.pexels.com/photos/3933881/pexels-photo-3933881.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      alt: "A River Flowing Image",
      title: "River Flow",
      description: "A serene river flowing through a lush green valley.",
      tags: ["Nature", "River", "Landscape"],
      height: 750,
      likes: 180,
      prompt:
        "A calm river winding through a vibrant green valley, with soft sunlight.",
      orientation: "horizontal",
      color: "green",
      gridSize: "wide",
    },
    {
      id: "q4",
      src: "https://images.pexels.com/photos/5409751/pexels-photo-5409751.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      alt: "A cloudy Mountain Image",
      title: "Cloudy Mountain",
      description: "Majestic mountains shrouded in mystical clouds.",
      tags: ["Nature", "Mountain", "Clouds"],
      height: 750,
      likes: 95,
      prompt:
        "A dramatic view of a mountain peak partially obscured by swirling clouds.",
      orientation: "horizontal",
      color: "gray",
      gridSize: "normal",
    },
    {
      id: "q5",
      src: "https://images.pexels.com/photos/4101555/pexels-photo-4101555.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      alt: "A Winter Rainbow Image",
      title: "Winter Rainbow",
      description: "A rare and beautiful rainbow appearing in a winter sky.",
      tags: ["Nature", "Winter", "Rainbow"],
      height: 750,
      likes: 130,
      prompt:
        "A vibrant rainbow arching over a snow-covered landscape during winter.",
      orientation: "horizontal",
      color: "white",
      gridSize: "normal",
    },
    {
      id: "q6",
      src: "https://images.pexels.com/photos/443446/pexels-photo-443446.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      alt: "A Clean Mountain Lake",
      title: "Mountain Lake",
      description:
        "Crystal clear waters of a mountain lake reflecting the sky.",
      tags: ["Nature", "Lake", "Mountain"],
      height: 750,
      likes: 280,
      prompt:
        "An aerial view of a pristine mountain lake with clear blue water and surrounding pine trees.",
      orientation: "horizontal",
      color: "blue",
      gridSize: "wide",
    },
    {
      id: "q7",
      src: "https://images.pexels.com/photos/1142950/pexels-photo-1142950.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      alt: "Shining Stars Image",
      title: "Shining Stars Again",
      description: "Another stunning capture of the night sky.",
      tags: ["Night", "Stars", "Sky"],
      height: 750,
      likes: 200,
      prompt:
        "A different perspective of a starry night, with a focus on a specific constellation.",
      orientation: "horizontal",
      color: "dark",
      gridSize: "normal",
    },
    {
      id: "q8",
      src: "https://images.pexels.com/photos/1032650/pexels-photo-1032650.jpeg?auto=compress&cs=tinysrgb&w=800&h=1200&dpr=2",
      alt: "Cityscape at Sunset",
      title: "City Sunset",
      description:
        "Vibrant city skyline at dusk. A beautiful blend of urban architecture and natural light.",
      tags: ["City", "Sunset", "Urban"],
      height: 1200,
      likes: 450,
      prompt:
        "A wide shot of a modern city at sunset, with warm orange and purple hues in the sky, reflecting on glass buildings.",
      orientation: "vertical",
      color: "orange",
      gridSize: "large",
    },
    {
      id: "q9",
      src: "https://images.pexels.com/photos/1054218/pexels-photo-1054218.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&dpr=2",
      alt: "Mountain Lake",
      title: "Alpine Serenity",
      description:
        "Tranquil lake surrounded by majestic snow-capped mountains under a clear sky.",
      tags: ["Nature", "Mountain", "Lake"],
      height: 1000,
      likes: 389,
      prompt:
        "A serene alpine lake reflecting snow-capped peaks, with crystal clear water and a deep blue sky.",
      orientation: "vertical",
      color: "blue",
      gridSize: "normal",
    },
    {
      id: "q10",
      src: "https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg?auto=compress&cs=tinysrgb&w=800&h=1200&dpr=2",
      alt: "Abstract Light Trails",
      title: "Light Trails",
      description:
        "Dynamic light streaks in motion, creating an abstract and futuristic pattern.",
      tags: ["Abstract", "Light", "Motion"],
      height: 1200,
      likes: 510,
      prompt:
        "Long exposure photography of car lights on a winding road at night, creating vibrant light trails against a dark background.",
      orientation: "vertical",
      color: "purple",
      gridSize: "normal",
    },
    {
      id: "q11",
      src: "https://images.pexels.com/photos/1122408/pexels-photo-1122408.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&dpr=2",
      alt: "Forest Road",
      title: "Enchanted Path",
      description:
        "A winding road through a dense, green forest, inviting exploration.",
      tags: ["Nature", "Forest", "Road"],
      height: 1000,
      likes: 275,
      prompt:
        "A narrow, winding dirt road disappearing into a dense, sun-dappled forest, with tall trees and lush undergrowth.",
      orientation: "vertical",
      color: "green",
      gridSize: "normal",
    },
    {
      id: "q12",
      src: "https://images.pexels.com/photos/113338/pexels-photo-113338.jpeg?auto=compress&cs=tinysrgb&w=800&h=1200&dpr=2",
      alt: "Coffee Cup",
      title: "Morning Brew",
      description:
        "A cozy moment with a steaming cup of coffee on a rustic wooden table.",
      tags: ["Food", "Lifestyle", "Coffee"],
      height: 1200,
      likes: 150,
      prompt:
        "A close-up shot of a white ceramic coffee cup with steam rising, placed on a wooden table next to a window with soft morning light.",
      orientation: "vertical",
      color: "brown",
      gridSize: "large",
    },
    {
      id: "q13",
      src: "https://images.pexels.com/photos/1169084/pexels-photo-1169084.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&dpr=2",
      alt: "Desert Landscape",
      title: "Arid Beauty",
      description:
        "Vast, untouched desert landscape with rolling sand dunes under a clear blue sky.",
      tags: ["Nature", "Desert", "Landscape"],
      height: 1000,
      likes: 60,
      prompt:
        "An expansive desert landscape featuring undulating sand dunes, with clear blue skies and harsh sunlight casting long shadows.",
      orientation: "vertical",
      color: "yellow",
      gridSize: "normal",
    },
    {
      id: "q14",
      src: "https://images.pexels.com/photos/1206059/pexels-photo-1206059.jpeg?auto=compress&cs=tinysrgb&w=800&h=1200&dpr=2",
      alt: "Waterfall",
      title: "Cascading Waters",
      description:
        "A powerful waterfall in a lush, green environment, surrounded by vibrant foliage.",
      tags: ["Nature", "Waterfall", "Forest"],
      height: 1200,
      likes: 180,
      prompt:
        "A majestic waterfall with clear, powerful water cascading down rocks into a pool, surrounded by dense, green rainforest.",
      orientation: "vertical",
      color: "green",
      gridSize: "normal",
    },
    {
      id: "q15",
      src: "https://images.pexels.com/photos/1229861/pexels-photo-1229861.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&dpr=2",
      alt: "Geometric Pattern",
      title: "Modern Geometry",
      description:
        "Intricate patterns in modern architecture, showcasing repetitive geometric forms.",
      tags: ["Abstract", "Architecture", "Pattern"],
      height: 1000,
      likes: 95,
      prompt:
        "A close-up of a modern building facade with repeating geometric patterns, focusing on lines and shadows.",
      orientation: "square",
      color: "gray",
      gridSize: "normal",
    },
    {
      id: "q16",
      src: "https://images.pexels.com/photos/1236701/pexels-photo-1236701.jpeg?auto=compress&cs=tinysrgb&w=800&h=1200&dpr=2",
      alt: "Autumn Leaves",
      title: "Fall Colors",
      description:
        "Vibrant autumn leaves scattered on the ground, a tapestry of red, orange, and gold.",
      tags: ["Nature", "Autumn", "Leaves"],
      height: 1200,
      likes: 110,
      prompt:
        "A ground-level shot of a forest floor covered in colorful autumn leaves, with soft, diffused sunlight.",
      orientation: "square",
      color: "red",
      gridSize: "normal",
    },
    {
      id: "q17",
      src: "https://images.pexels.com/photos/1269968/pexels-photo-1269968.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&dpr=2",
      alt: "Ocean Sunset",
      title: "Golden Hour",
      description:
        "A breathtaking sunset over the calm ocean, with a golden glow reflecting on the water.",
      tags: ["Nature", "Sunset", "Ocean"],
      height: 1000,
      likes: 250,
      prompt:
        "A wide shot of the ocean at sunset, with a vibrant orange and pink sky, and the sun's reflection on the water.",
      orientation: "square",
      color: "orange",
      gridSize: "large",
    },
    {
      id: "q18",
      src: "https://images.pexels.com/photos/1309767/pexels-photo-1309767.jpeg?auto=compress&cs=tinysrgb&w=800&h=1200&dpr=2",
      alt: "City Night Lights",
      title: "Neon City",
      description:
        "Bright neon signs illuminating a bustling city street at night, creating a vibrant urban scene.",
      tags: ["City", "Night", "Neon"],
      height: 1200,
      likes: 190,
      prompt:
        "A busy city street at night, with blurred car lights and sharp, colorful neon signs illuminating the scene.",
      orientation: "square",
      color: "dark",
      gridSize: "normal",
    },
    {
      id: "q19",
      src: "https://images.pexels.com/photos/1317232/pexels-photo-1317232.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&dpr=2",
      alt: "Abstract Paint",
      title: "Fluid Art",
      description:
        "Abstract painting with swirling colors, creating a sense of movement and depth.",
      tags: ["Art", "Abstract", "Fluid"],
      height: 1000,
      likes: 105,
      prompt:
        "A macro shot of fluid acrylic paint swirling, creating abstract patterns with vibrant blues, greens, and purples.",
      orientation: "square",
      color: "blue",
      gridSize: "normal",
    },
    {
      id: "q20",
      src: "https://images.pexels.com/photos/3408744/pexels-photo-3408744.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      alt: "Northern Winter Sky Image",
      title: "Northern Winter Sky",
      description:
        "A breathtaking view of the aurora borealis over a winter landscape.",
      tags: ["Nature", "Winter", "Aurora"],
      height: 750,
      likes: 345,
      prompt:
        "A wide shot of the northern lights dancing over a snowy forest, with clear stars in the sky.",
      orientation: "horizontal",
      color: "blue",
      gridSize: "large",
    },
    {
      id: "q21",
      src: "https://images.pexels.com/photos/1142950/pexels-photo-1142950.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      alt: "Shining Stars Image",
      title: "Shining Stars",
      description: "A beautiful night sky filled with countless shining stars.",
      tags: ["Night", "Stars", "Sky"],
      height: 750,
      likes: 210,
      prompt:
        "Long exposure of a starry night sky over a dark landscape, focusing on the Milky Way.",
      orientation: "horizontal",
      color: "dark",
      gridSize: "wide",
    },
    {
      id: "q22",
      src: "https://images.pexels.com/photos/3933881/pexels-photo-3933881.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      alt: "A River Flowing Image",
      title: "River Flow",
      description: "A serene river flowing through a lush green valley.",
      tags: ["Nature", "River", "Landscape"],
      height: 750,
      likes: 180,
      prompt:
        "A calm river winding through a vibrant green valley, with soft sunlight.",
      orientation: "horizontal",
      color: "green",
      gridSize: "wide",
    },
  ];

  
   